[package]
name = "assembler"
version = "0.2.1"
authors = ["Jonathon Pendleury <jonathon.pendlebury@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.8", features = ["macros"] }
clap = "2.33.3"